name: Deploy Docs to GitHub Pages

# build the documentation whenever there are new commits on main with tag
on:
  push:
    tags:
      - '*'

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install all dependencies + build defined in pyproject.toml
      - run: pip install .[build]
      # Run pdoc3 to build the documentation
      - run: pdoc gmag -o docs/ --html
      # pdoc generates html in docs/gmag/, need to move it up one level to docs/
      - run: mv docs/gmag/* docs/ # note: all this is not committed to the repo

      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
